name: preview

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dataman_preview:
    
    runs-on: ubuntu-latest
    steps:
      #convert the github secrets tokens into the env files

      

      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.DATAMAN_EXPO_ACCESS_TOKEN }}

      - name: ğŸ‘· Build packages
        run: pnpm run -w build 

      - name: ğŸš€ Publish preview
        working-directory: apps/Dataman
        run: expo publish --release-channel=pr-${{ github.event.number }}

      - name: ğŸ’¬ Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          project: apps/Dataman
          channel: pr-${{ github.event.number }}
  vvclub_preview:
    
    runs-on: ubuntu-latest
    steps:
      #convert the github secrets tokens into the env files

      

      - name: ğŸ— Setup repository
        uses: actions/checkout@v3

      - name: ğŸ— Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.DATAMAN_EXPO_ACCESS_TOKEN }}

      - name: ğŸ‘· Build packages
        run: pnpm run -w build 

      - name: ğŸš€ Publish preview
        working-directory: apps/VvClub
        run: expo publish --release-channel=pr-${{ github.event.number }}

      - name: ğŸ’¬ Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          project: apps/VvClub
          channel: pr-${{ github.event.number }}
